spring:
  spring:
    cloud:
      consul:
        host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
        port: ${SPRING_CLOUD_CONSUL_PORT:8500}
        discovery: voiture-service
  application:
    name: voiture-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/Micro-voituredb?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver




server:
  port: 8082




management:
  endpoints:
    web:
      exposure:
        include: '*'
